clear all;
syms d_1 d_2 n
%% Analysis for role "F2", the source is from the function run in class algs.vrl2p.Party2, the Algorithm is VRL-2P.
f = sym(zeros(1,6));
% [Code from] MWNumericArray Q=MatComputeHelper.randOrthMat(d);
g = [0 , d_2^2 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] MWNumericArray X=MatComputeHelper.mul(X0, Q);
g = [0 , d_2^2*n , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] MWNumericArray Xt = MatComputeHelper.mul(MatComputeHelper.transpose(X),omiga);
g = [0 , n*d_2 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] MWNumericArray F2=coMul(X, algInfo.getTestId()*Common.ROOMID_BIAS+1, 2);
g = tColMul(d_1,d_2,n);
g = g(2,:);
f = f + g;
% [Code from] EncMat encF1=(EncMat) msg.getObj();
g = [0 , 0 , 0 , 0 , d_1*d_2 , 0];
f = f + g;
% [Code from] EncMat M12=encF1.add(F2);
g = [d_1*d_2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] sendMessage(algInfo.getParty(1), 21, M12);
g = [0 , 0 , d_1*d_2 , 0 , 0 , 0];
f = f + g;
% [Code from] MatComputeHelper.mul(MatComputeHelper.eye(d), algInfo.getLambda()*omiga));
g = [0 , d_2^2*n+d_2 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] MWNumericArray C = MatComputeHelper.inv(M22);
g = [0 , d_2^3 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] EncMat encC=new EncMatMultThread(C,pubKey);
g = [d_2^2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] sendMessage(algInfo.getParty(1), 21, encC);
g = [0 , 0 , d_2^2 , 0 , 0 , 0];
f = f + g;
% [Code from] EncMat encCt = (EncMat) msg.getObj();
g = [0 , 0 , 0 , 0 , d_1^2 , 0];
f = f + g;
% [Code from] EncMat encR=mul(encCt, M12);
g = tMMA(d_1,d_2,d_1);
g = g(1,:);
f = f + g;
% [Code from] encR=mul(M21, encR);
g = tMMA(d_2,d_2,d_1);
g = g(1,:);
f = f + g;
% [Code from] encR=new EncMatMultThread(M22, pubKey).subtract(encR);
g = [d_2^2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] encR=inv(encR);
g = tMIA(d_2);
g = g(1,:);
f = f + g;
% [Code from] MWNumericArray r12=coMul(y, algInfo.getTestId()*Common.ROOMID_BIAS+2, 2);
g = tColMul(d_1,1,n);
g = g(2,:);
f = f + g;
% [Code from] EncMat encr12=new EncMatMultThread(r12, pubKey);
g = [d_1 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] sendMessage(algInfo.getParty(1), 21, encr12);
g = [0 , 0 , d_1 , 0 , 0 , 0];
f = f + g;
% [Code from] MWNumericArray r2=MatComputeHelper.mul(Xt, y);
g = [0 , d_2*n , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] EncMat encu2=encR.mul(r2);
g = [d_2^2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] sendMessage(algInfo.getParty(1), 21, encu2);
g = [0 , 0 , d_2 , 0 , 0 , 0];
f = f + g;
% [Code from] EncMat encu1=(EncMat) msg.getObj();
g = [0 , 0 , 0 , 0 , d_1 , 0];
f = f + g;
% [Code from] EncMat encv2=EncMat.mul2(C, mul(M21, encu1));
g = tMMA(d_2,1,d_1);
g = g(1,:);
f = f + g;
% [Code from] //<Same as Last Line> EncMat encv2=EncMat.mul2(C, mul(M21, encu1));
g = [d_2^2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] EncMat encw = encu2.subtract(encv2);
g = [d_2 , 0 , 0 , 0 , 0 , 0];
f = f + g;
% [Code from] res = MatComputeHelper.mul(Q,decr(encw));
g = tDecr(d_2,1);
g = g(1,:);
f = f + g;
% [Code from] //<Same as Last Line> res = MatComputeHelper.mul(Q,decr(encw));
g = [0 , d_2^2 , 0 , 0 , 0 , 0];
f = f + g;
res = f;
disp('Analysis for role "F2", the source is from the function run in class algs.vrl2p.Party2, the Algorithm is VRL-2P.');
showRes(res)